# docker-compose.yml
services:
  vergo_back:
    image: vergo_back
    container_name: vergo_back
    restart: always
    volumes:
      - ./images:/usr/src/app/images
    networks:
      - interservices

networks:
  interservices:
    external: true