###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query exercices {
  exercices {
    id
    slug
    title {
      lang
      value
    }
    description {
      lang
      value
    }
    image
  }
}