###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  getUserKpis {
    sessions {
      id
      label
      date
      duration
    }
  }
}