###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainings {
  trainings {
    id
    slug
    gender
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainingsPaginable {
  trainingsPaginable {
    nodes {
      id
      slug
      gender
    }
    totalCount
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainingsPaginated {
  trainingsPaginated(limit:2, orderBy: { field: "id", order: DESC }) {
    nodes {
      id
      slug
      gender
    }
    totalCount
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  training_normalized (
    dto: {
      id: "66b1ecee43812dbcda7843fa"
    }
  ) {
    slugs
    type
    duration
    ite
    weight
  }
}