###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  getUserKpis {
    sessions {
      id
      label
      date
      duration
      completed
    }
    activities {
      date
      duration
    }
    gamification {
      xp
      level
      levelXp
      levelXpToNext
      levelProgressPct
      league {
        code
        minutes
        threshold
        nextCode
        nextThreshold
      }
      weeklyLeague {
        code
        minutes
        threshold
        nextCode
        nextThreshold
      }
    }
    badges {
      code
      earned
      earnedAt
      meta
    }
  }
}