###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {
  training_create (
    dto: {
      slug: "new-training-slug-3"
      label: "Description of the new training 3"
      gender: "male"
      workout: [
        {
          slug: "warm-up"
          sets: [
            {
              rep: 1
              slugs: [
                "jump rope"
              ]
              duration: 40
              rest: 20
            },
            {
              rep: 2
              slugs: [
                "hip circles"
                "stretch_spinal_twist"
              ],
              duration: 30
              rest: 20
            }
          ]
        },
        {
          slug: "abdo"
          sets: [
            {
              rep: 1
              slugs: [
                "crunch"
              ]
              duration: 40
              rest: 20
            }
          ]
        }
      ]
    }
  ) {
    id
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query training {
  training(dto: { id: "66b0bb7ca4d5b1fc4a27332e" }) {
    id
    slug
    label
    gender
    workout {
      slug
      sets {
        rep
        slugs
        ite
        weight
        duration
        rest
        pause
        sets {
          rep
          slugs
          ite
          weight
          duration
          rest
          pause
          sets {
            rep
            slugs
            ite
            weight
            duration
            rest
            pause
          }
        }
      }
    }
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainings {
  trainings {
    id
    slug
    gender
    creator_id
    creator {
      id
      code
    }
    contributors_id
    contributors {
      id
      code
    }
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainingsPaginable {
  trainingsPaginable {
    nodes {
      id
      slug
      gender
    }
    totalCount
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainingsPaginated {
  trainingsPaginated(limit:2, orderBy: { field: "id", order: DESC }) {
    nodes {
      id
      slug
      gender
    }
    totalCount
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  training_normalized (
    dto: {
      id: "66af92ab43812dbcda7843e6"
    }
  ) {
    slugs
    type
    duration
    ite
    weight
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {
  training_update (
    dto: {
      id: "66af92ab43812dbcda7843e6",
      slug: "test"
    }
  )
}